added ids and set which tests are critical

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,6 +32,7 @@ jobs:
 
       - name: Run general tests for all changes
         continue-on-error: true
+        id: general_tests
         if: always()  # Run general tests regardless of specific files changing
         run: pytest tests/0_general/*
 
@@ -40,11 +41,12 @@ jobs:
         id: changes
         run: |
           git fetch origin ${{ github.event.before }} --depth=1
-          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
+          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' > changed_files.txt
           cat changed_files.txt
           
       - name: Test for Debugging Strings
         continue-on-error: true
+        id: debugging_strings
         run: |
           if [ -s changed_files.txt ]; then
             CHANGED_FILES=$(cat changed_files.txt)
@@ -83,9 +85,17 @@ jobs:
 
       - name: Run relevant tests
         continue-on-error: true
+        id: game_tests
         if: env.GAMES != ''
         run: |
           echo "Running tests with GAMES=$GAMES"
           pytest tests/1_games/test_defaults.py
           pytest tests/1_games/test_obj.py
+
+      # Fail Workflow if Any Critical Test Failed
+      - name: Fail Workflow if Any Critical Test Failed
+        if: steps.general_tests.outcome == 'failure' || steps.game_tests.outcome == 'failure' || steps.debugging_strings.outcome == 'failure'
+        run: |
+          echo "One or more critical tests have failed. Failing workflow."
+          exit 1
 
